# Example synonyms file. Generated version will overwrite config/synonyms.yaml
# Structure:
# synonyms:
#   - canonical: e-ink
#     terms:
#       - epd
#       - e paper
#       - e ink
synonyms: []
